// File generated by direct Firebase configuration from the provided google-services.json
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8aAzpQbrPObYf6cF1rGeE2XIZJjGHFQA',
    appId: '1:338458102155:web:839931a6d9671d10ca478e', // You must get this from Firebase Console
    messagingSenderId: '338458102155',
    projectId: 'mobile-application-1f011',
    storageBucket: 'mobile-application-1f011.firebasestorage.app',
    authDomain: 'mobile-application-1f011.firebaseapp.com', // Added authDomain for Web
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8aAzpQbrPObYf6cF1rGeE2XIZJjGHFQA',
    appId: '1:338458102155:android:4ff5f68171d79274ca478e',
    messagingSenderId: '338458102155',
    projectId: 'mobile-application-1f011',
    storageBucket: 'mobile-application-1f011.firebasestorage.app',
  );
}
